-- Run with psql -X -v ON_ERROR_STOP=1 -f backend/src/test/sql/migration-check.sql
-- Use a disposable PostgreSQL database. Everything is rolled back, including the test schema.
\set ON_ERROR_STOP on
\encoding UTF8
BEGIN;
CREATE SCHEMA vibebass_migration_check;
SET LOCAL search_path TO vibebass_migration_check;

\ir ../../main/resources/db/migration/V1__init_schema.sql
INSERT INTO songs (title, youtube_video_id, anchor_points, deleted_at) VALUES
    ('Whiplash[tab].pdf', 'dQw4w9WgXcQ', '[{"timeSec":0,"scrollPixel":200}]', NULL),
    ('한 페이지가 될 수 있게 [tab].pdf', 'dQw4w9WgXcQ',
     '[{"timeSec":10,"scrollPixel":500,"pagePosition":1.25}]', TIMESTAMP '2026-09-13 10:00:00');
CREATE TEMP TABLE original_songs AS TABLE songs;

\ir ../../main/resources/db/migration/V2__align_song_columns.sql
DO $$
BEGIN
    IF EXISTS (TABLE original_songs EXCEPT TABLE songs) OR (SELECT count(*) FROM songs) <> 2 THEN
        RAISE EXCEPTION 'Migration changed existing songs, JSON anchors or soft-delete state';
    END IF;
END $$;

-- Emulate the legacy Hibernate layout: varchar(255), identity IDs, no SQL defaults.
ALTER TABLE songs ALTER COLUMN youtube_video_id TYPE VARCHAR(255),
    ALTER COLUMN id DROP DEFAULT,
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    ALTER COLUMN anchor_points DROP DEFAULT,
    ALTER COLUMN created_at DROP DEFAULT,
    ALTER COLUMN updated_at DROP DEFAULT;
INSERT INTO songs (title, youtube_video_id, anchor_points, created_at, updated_at)
VALUES ('Legacy value longer than V1', repeat('x', 120), '[]', NOW(), NOW());

\ir ../../main/resources/db/migration/V2__align_song_columns.sql
INSERT INTO songs (title, youtube_video_id) VALUES ('Default values', 'dQw4w9WgXcQ');
DO $$
BEGIN
    IF EXISTS (TABLE original_songs EXCEPT TABLE songs) OR (SELECT count(*) FROM songs) <> 4 THEN
        RAISE EXCEPTION 'Legacy migration lost rows';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM songs WHERE id = 100 AND youtube_video_id = repeat('x', 120)) THEN
        RAISE EXCEPTION 'Legacy identity or long video ID was changed';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM songs WHERE id = 101 AND anchor_points = '[]'::jsonb
                   AND created_at IS NOT NULL AND updated_at IS NOT NULL AND deleted_at IS NULL) THEN
        RAISE EXCEPTION 'SQL defaults or identity generation were not restored';
    END IF;
END $$;
ROLLBACK;
\echo Migration checks passed; test schema rolled back.
